export const products = [{
        id: "cmt3tLy6uuDnNMNW9qHr",
        title: "Sofá de 3 plazas",
        price: 25000,
        stock: 10,
        description: "Sofá cómodo de 3 plazas en color gris.",
        category: "Living",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1725985886/new-zealand-hotel-5_adxiuo.jpg",
    },
    {
        id: "YA3H7EoWPmFlok8GmwAO",
        title: "Mesa de Centro",
        price: 12000,
        stock: 15,
        description: "Mesa de centro de madera con acabado en roble.",
        category: "Living",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1725987795/images_pdw2hb.jpg",
    },
    {
        id: "Eb4vGnlJVoRzK1epuQ81",
        title: "Sommier King Size",
        price: 45000,
        stock: 8,
        description: "Sommier King Size con colchón incluido.",
        category: "Dormitorio",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1725986486/ep-2ITAVTYABBC77BPXJ6KLJAM4EI_ykbzza.jpg", // Cambia la URL a una imagen real
    },
    {
        id: "jn7dKEQ9orvjeyFEhgWc",
        title: "Cómoda de 4 cajones",
        price: 18000,
        stock: 5,
        description: "Cómoda de 4 cajones en color blanco, ideal para el dormitorio.",
        category: "Dormitorio",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1728336054/comoda-4-cajones-color-naturale-gris-tormenta-_nu9t1a.jpg", // Cambia la URL a una imagen real
    },
    {
        id: "bltM6Z3d2QSbPwSWpnnK",
        title: "Silla de Patio Apilable",
        price: 4500,
        stock: 10,
        description: "Silla de patio apilable en metal, resistente a la intemperie.",
        category: "Patio",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1728336260/images_nxwy1v.jpg"
    },
    {
        id: "C81aE0Q2X1lvrs37ZlSt",
        title: "Mesa de Patio Redonda",
        price: 8500,
        stock: 8,
        description: "Mesa redonda de patio en madera tratada, perfecta para reuniones.",
        category: "Patio",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1728336428/mesa_patio_redonda_f8tyfm.jpg"
    },
    {
        id: "mkZ1nsuCr0kQ0CDOMfu1",
        title: "Tumbona de patio",
        price: 12000,
        stock: 6,
        description: "Tumbona de patio ajustable, ideal para tomar el sol.",
        category: "Patio",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1728336489/tumbona-seagull-de-aluminio-blanco_orig_jc73te.jpg"
    },
    {
        id: "QKIHWn4FsK7b8LHDmtlA",
        title: "Mesa de Comedor Extensible",
        price: 32000,
        stock: 7,
        description: "Mesa de comedor extensible con acabado en nogal, ideal para 6-8 personas.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729791214/mesaComedorExtensible_ru1zs7.jpg",
    },
    {
        id: "Mzr0NJi0BC9odNzh813s",
        title: "Juego de Sillas de Comedor",
        price: 22000,
        stock: 12,
        description: "Juego de 4 sillas de comedor tapizadas en tela gris con patas de madera.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729791378/juegoSillasComedor_ijzhes.jpg",
    },
    {
        id: "k0BaXHEY4pjmONCVjh27",
        title: "Vitrina de Comedor",
        price: 28000,
        stock: 5,
        description: "Vitrina de comedor de dos puertas con estantes de vidrio, perfecta para exhibir vajillas.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729790774/vitrinaDeComedor_omh0wm.jpg",
    },
    {
        id: "yzBEBWBX48iqtThWVxkY",
        title: "Aparador de Comedor",
        price: 26000,
        stock: 4,
        description: "Aparador de comedor en madera maciza con amplio espacio de almacenamiento.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729792801/aparador_fsdul7.jpg",
    },
    {
        id: "pZPelm9CAGUTh1uU5O7b",
        title: "Silla de Comedor de Cuero",
        price: 7500,
        stock: 20,
        description: "Silla de comedor con asiento de cuero sintético y estructura de acero.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729791873/sillaCueroAcero_i2fewf.jpg",
    },
    {
        id: "BbkXS7UexXunBNVrM7LS",
        title: "Mesa Redonda de Comedor",
        price: 27000,
        stock: 6,
        description: "Mesa redonda de comedor con superficie de mármol y base de acero dorado.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729792448/mesaRedonda_dya8mi.jpg",
    },
    {
        id: "6qlVle73MvSSb5yfvIpN",
        title: "Buffet de Comedor",
        price: 24500,
        stock: 3,
        description: "Buffet de comedor con puertas correderas y estantes ajustables.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729791518/buffetComedor_yoeeqd.jpg",
    },
    {
        id: "OmnLXbUnZNHfiVlB0Ryz",
        title: "Silla Tapizada de Comedor",
        price: 9800,
        stock: 15,
        description: "Silla tapizada en terciopelo azul oscuro con patas de metal dorado.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729792604/sillaAzul_nyzffz.jpg",
    },
    {
        id: "K8nBkpp9anqV2AXxOJYY",
        title: "Lámpara de Comedor Colgante",
        price: 18500,
        stock: 10,
        description: "Lámpara colgante moderna con 6 luces y diseño industrial.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729791752/lamparaColgante_dwmefn.jpg",
    },
    {
        id: "3jcTAqkjtM6WkZvtcQ4V",
        title: "Centro de Mesa Decorativo",
        price: 6500,
        stock: 25,
        description: "Centro de mesa decorativo de cerámica en tonos neutros, ideal para comedores minimalistas.",
        category: "Comedor",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729792032/centroMesa_nocecm.jpg",
    },
    {
        id: "9ZZHGYPH3BF7zNdbHqfC",
        title: "Biblioteca Moderna de Madera",
        price: 32000,
        stock: 8,
        description: "Biblioteca moderna de madera con 5 estantes, ideal para libros y decoración.",
        category: "Biblioteca",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729793184/bibliotecaModerna_zo9dvq.jpg",
    },
    {
        id: "WHWb2KWIKtChj4rLczuC",
        title: "Estantería Biblioteca de Metal",
        price: 27000,
        stock: 5,
        description: "Biblioteca de metal con 5 niveles, diseño industrial y resistente.",
        category: "Biblioteca",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729793277/bibliotecaModerna5Niveles_df00jb.jpg",
    },
    {
        id: "i7yQoeVQZUMxSmZQwJib",
        title: "Biblioteca Clásica de Roble",
        price: 45000,
        stock: 3,
        description: "Biblioteca clásica de roble con puertas de vidrio, perfecta para hogares elegantes.",
        category: "Biblioteca",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729793350/bibliotecaRoble_tqcdby.jpg",
    },
    {
        id: "s7bi02UAklts4vHg4c8X",
        title: "Biblioteca Modular",
        price: 28000,
        stock: 10,
        description: "Biblioteca modular con estantes ajustables, perfecta para adaptarse a cualquier espacio.",
        category: "Biblioteca",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729793446/bibliotecaModular_flojqn.jpg",
    },
    {
        id: "k5QycEkLkmniaSHgWjfm",
        title: "Biblioteca con Escritorio Incorporado",
        price: 39000,
        stock: 6,
        description: "Biblioteca con escritorio integrado, ideal para espacios pequeños y funcionales.",
        category: "Biblioteca",
        imgUrl: "https://res.cloudinary.com/dlec64dbi/image/upload/v1729793544/bibliotecaEscritorio_zoxw1j.jpg",
    }
];